services:
  inventory-database:
    image: postgres:18-alpine
    container_name: inventory-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5442:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  inventory_db_data:
